### ISSUE TITLE
Добавить описание лимита для вложенной коллекции positions

### ISSUE THREAD

**Issue by wmakeev** [moysklad/api-remap-1.2-doc#124]
Отразить в документации, что лимиты при работе с вложенным полем `positions` в рамках документа и с помощью специальных ресурсов увеличены до 1000 элементов.

[По ограничению на кол-во обновляемых позиций в документах](https://support.moysklad.ru/hc/ru/community/posts/115007946768-%D0%9F%D0%BE-%D0%BE%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D1%8E-%D0%BD%D0%B0-%D0%BA%D0%BE%D0%BB-%D0%B2%D0%BE-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D1%8B%D1%85-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%B9-%D0%B2-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%85?page=1#community_comment_360001314118)

- В разделе **Общие сведения - Работа с позициями документов - Работа с позициями документов с помощью специальных ресурсов**, описание: `При создании новых позиций с помощью данных ресурсов, можно обходить ограничение в 100 позиций на документ` - не актуально.

- В разделе **Общие сведения -  Ограничения**, описание: `Также накладывается ограничение на максимальное число объектов (позиций, материалов, продуктов), передаваемых в одном массиве в запросе - не более 100 элементов.` - не актуально, как минимум в случае с позициями.

- В разделе **Общие сведения - Метаданные - Атрибуты расширенного объекта meta**, описание: `Максимальное количество элементов в списке равно 1000, для вложенных коллекций - 100.` - не актуально для вложенной коллекции `positions`.

**Comment by EReztsov** [comment]
Спасибо за замечание. Было исправлено где-то в июне 2020 года. Закрываю за ненадобностью.

PS: Раньше не смотрели в раздел Issues, отныне будем это делать. Если есть какие-нибудь неточности или предложения к улучшению документации, можно их оставлять в Issues.
