### ISSUE TITLE
Ошибка в документации Товара

### ISSUE THREAD

**Issue by dimontus** [moysklad/api-remap-1.2-doc#204]
![image](https://user-images.githubusercontent.com/7289720/97965151-fb33b000-1dca-11eb-97e2-01ac067771b9.png)
![image](https://user-images.githubusercontent.com/7289720/97965238-19011500-1dcb-11eb-86d1-ddf62380a170.png)
![image](https://user-images.githubusercontent.com/7289720/97965288-2b7b4e80-1dcb-11eb-9245-9d7c28f84122.png)

В дукоментации указано что minPrice - это double,
а buyPrice - Array(Object), хотя на самом деле и то и другое это Object вида
`
{
        "value": 500,
        "currency": {
          "meta": {
            "href": "https://online.moysklad.ru/api/remap/1.2/entity/currency/10772c12-36e7-11e7-8a7f-40d000000097",
            "metadataHref": "https://online.moysklad.ru/api/remap/1.2/entity/currency/metadata",
            "type": "currency",
            "mediaType": "application/json"
          }
        }
      }
`

**Comment by segorov12** [comment]
Документацию поправили
