### ISSUE TITLE
Нет информации по фильтрам updatedFrom и updatedTo в документации для api 1.2

### ISSUE THREAD

**Issue by Matvienkden** [moysklad/api-remap-1.2-doc#225]
Нет информации по фильтрам updatedFrom и updatedTo в документации для api 1.2
Скрин из api 1.1

![image](https://user-images.githubusercontent.com/56012442/104849760-4d399b80-590d-11eb-9d18-72ddf0513a0a.png)

**Comment by EReztsov** [comment]
Здравствуйте. Это связано с тем, что в Remap 1.2 этих фильтров нет. Вместо updatedFrom/updatedTo можно использовать фильтрацию по полю updated. Например, `updatedTo=` эквивалентно `filter=updated<` .

Параметр updatedBy упразднен, ему эквивалента в Remap 1.2 нет.
