### ISSUE TITLE
phoneCall and counterparty

### ISSUE THREAD

**Issue by Caligulaaa** [moysklad/api-remap-1.2-doc#280]
Operating system: ✍️ TODO
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
Browser version(s): ✍️ TODO
Ruby version (run `ruby -v`):  ✍️ TODO

---

✍️ TODO write your issue here

1) Список звонков!!!, get запрос отсутсвует в документации, никак нельзя получить ни список ID ни даных, зато можна посмотреть даные по звонку, а где ID брать хз
![Знімок екрана  о 11 00 41](https://user-images.githubusercontent.com/49589055/116806437-a41e5600-ab35-11eb-86e1-a95f13537e0f.png)
![Знімок екрана  о 10 56 52](https://user-images.githubusercontent.com/49589055/116806358-1e020f80-ab35-11eb-97e5-ff15fc2b5152.png)
![Знімок екрана  о 10 57 29](https://user-images.githubusercontent.com/49589055/116806367-32dea300-ab35-11eb-9848-bb96097f2e71.png)

2) PUT запрос "https://online.moysklad.ru/api/remap/1.2/entity/counterparty"
 1. На основной странице отображает дату создания
![Знімок екрана  о 11 08 45](https://user-images.githubusercontent.com/49589055/116806581-c6fd3a00-ab36-11eb-9d5c-3c4470d6ed29.png)

При переходе для правки отсутсвует, стоит поле, как обезательное, и при изменениях требует указать.

![Знімок екрана  о 11 09 40](https://user-images.githubusercontent.com/49589055/116806597-e72cf900-ab36-11eb-882b-bdd34cd3ea29.png)

 2. При GET запросе дату дает, при PUT запросе требует и даже если указать полученую дату с GET в PUT всеравно требует и выдает ошибку 3000, как обязательное поле
![Знімок екрана  о 11 20 34](https://user-images.githubusercontent.com/49589055/116806846-6c64dd80-ab38-11eb-9ad5-6000f11b0df8.png)

**Comment by tortEzra** [comment]
PUT запрос ошибся, не думал, что есть конструктор, где было создано доп поле + обязательное с датой.
Всеравно странно, когда создавались контрагенты, поле, что указано обязательное, оно пустое

**Comment by IvchenkoAlexandr** [comment]
Здравстуйте. Вопросы по Phone API лучше задавать в https://github.com/moysklad/api-phone-1.0-doc/issues. Насколько я знаю, список звонков не был сделан из соображений безопасности
