### ISSUE TITLE
Не работает фильтрация комплектов по дополнительным полям

### ISSUE THREAD

**Issue by gusya1** [moysklad/api-remap-1.2-doc#373]
Запрос такого вида:
https://online.moysklad.ru/api/remap/1.2/entity/bundle?limit=1000&offset=0&filter=https://online.moysklad.ru/api/remap/1.2/entity/product/metadata/attributes/a2d0cb11-1a2f-11ec-0a80-07e3002824c5=True
Получаю ошибку:
Ошибка фильтрации: Тип сущности 'Good' в href поля фильтрации не совпадает с запрашиваемым 'Kit'

**Comment by IvchenkoAlexandr** [comment]
Здравствуйте. Иправлено
