### ISSUE TITLE
Нет фильтрации по группам товаров

### ISSUE THREAD

**Issue by serhiimakarov** [moysklad/api-remap-1.2-doc#395]
В документации JSON API 1.2 нет примеров запросов для фильтрации по группам товаров. 
На сайт необходимо выгрузить товары с определенных групп но API не позволяет этого сделать. 

Запрос по примеру ссылочного запроса:
```
https://online.moysklad.ru/api/remap/1.2/entity/product/?filter=productfolder=https://online.moysklad.ru/api/remap/1.2/entity/productfolder/some-product-folder-id
```

Пожалуйста добавьте данный фильтр для товаров.

**Comment by IvchenkoAlexandr** [comment]
Здравствуйте. Вы можете фильтровать по pathName. Пример: есть “Подгруппа 1”, которая входит в группу “Главаная группа”, тогда, чтобы найти товары в “Подгруппе 1”, следует сдалеть такой запрос: `https://online.moysklad.ru/api/remap/1.2/entity/product/?filter=pathName=Главная группа/Подгруппа 1`
