### ISSUE TITLE
Выгрузка каталога товаров по API

### ISSUE THREAD

**Issue by ipman750** [moysklad/api-remap-1.2-doc#424]
Здравствуйте, при выгрузка каталога по API, не правильно выгружаются цены, например цена 555, в мой склад она записана 555,00. При выгрузке по АPI, цена выгружается не 555, а 55500. Два нуля тоже включаются в цену как целое число.

**Comment by IvchenkoAlexandr** [comment]
Здравствуйте. Цены в API выводятся в копейках, поэтому два нуля и появились
