### ISSUE TITLE
Описание и расшифровка типа поля ГТД

### ISSUE THREAD

**Issue by wmakeev** [moysklad/api-remap-1.2-doc#436]
В разделе [Позиции возврата покупателя](https://dev.moysklad.ru/doc/api/remap/1.2/documents/#dokumenty-vozwrat-pokupatelq-vozwraty-pokupatelej) не верно указан тип поля `gtd` (указано как `String(255)`), по факту это объект с полем `name`. Для других сущностях указан ГТД с типом `Object`, но нет расшифровки поля (описания вложенных полей).

**Comment by IvchenkoAlexandr** [comment]
Здравствуйте. Добавили описание ГТД в блок “Сущности” 
https://dev.moysklad.ru/doc/api/remap/1.2/dictionaries/#suschnosti-gruzowaq-tamozhennaq-deklaraciq-gtd
