### ISSUE TITLE
CORS Problem No 'Access-Control-Allow-Origin' header is present on the requested resourc

### ISSUE THREAD

**Issue by bazhanoff** [moysklad/api-remap-1.2-doc#478]
Добрый день! Ошибка кросс-доменных запросов. Просьба посмотреть на одном из примеров ниже

Access to XMLHttpRequest at 'https://online.moysklad.ru/api/remap/1.2/report/orders/plotseries' from origin 'https://localhost:3000' || (https://your_domain.com) has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```javascript
fetch('https://online.moysklad.ru/api/remap/1.2/report/orders/plotseries', {
        method: 'GET',
        withCredentials: true,
        credentials: 'include',
        headers: {
            'Authorization': 'Bearer *',
            'Content-Type': 'application/jsonp'
        }
  })
```
**upd:** Ну то есть любой запрос к данному домену не разрешает обращаться с любого хоста.
Получается весь **api не работает** как минимум с **Sat Aug 27 2022 21:10:19 GMT+0300 (Moscow Standard Time)**

**Comment by bazhanoff** [comment]
upd: Ну то есть любой запрос к данному домену не разрешает обращаться с любого хоста.
Получается весь api не работает как минимум  с  `Sat Aug 27 2022 21:10:19 GMT+0300 (Moscow Standard Time)`

**Comment by epicfail169** [comment]
Тоже столкнулся с этой же проблемой

**Comment by Vurikus** [comment]
Добрый день. Из соображений безопасности, мы не поддерживаем кросс-доменные запросы. Предполагаемая работа с апи МоегоСклада - обращение к апи с использование своего сервера
