### ISSUE TITLE
Ошибка в документации - Удалить позицию Внутреннего заказа

### ISSUE THREAD

**Issue by apepenkov** [moysklad/api-remap-1.2-doc#515]
[В документации](https://dev.moysklad.ru/doc/api/remap/1.2/documents/#dokumenty-vnutrennij-zakaz-udalit-poziciu-vnutrennego-zakaza) прописано, что для удаления позиции из заказа, DELETE должен отправляться на 

`https://online.moysklad.ru/api/remap/1.2/entity/internalorder/positions/{positionID}`

Однако такой запрос выдаёт ошибку, что путь неверен. При 

`https://online.moysklad.ru/api/remap/1.2/entity/internalorder/{orderID}/positions/{positionID}` 

же запрос срабатывает.

**Comment by Vurikus** [comment]
Добрый день. Чтобы удалить конкретную позицию необходимы идентификаторы самой позиции (positionID) и документа (orderID). В документации опечатка. Спасибо за обращение, поправим
