### ISSUE TITLE
Здравствуйте!

### ISSUE THREAD

**Issue by Maksim123Z** [moysklad/api-remap-1.2-doc#549]
Здравствуйте!

При передачи данных из битрикса в мой склад API добавляет в заказы дубли.

Подскажите, с чем это может быть связано.

**Comment by Vurikus** [comment]
Здравствуйте. Чтобы нам лучше понять вашу ситуацию, нам необходимо больше данных. Если проблема еще актуальна, можете обратиться в техподдержку. Сделать это можно так:
![image](https://github.com/moysklad/api-remap-1.2-doc/assets/61026903/27a97223-3788-4dbd-aca6-075feeef23d0)
И чтобы попасть сразу на нужного специалиста выбрать одну из двух тем:
![image](https://github.com/moysklad/api-remap-1.2-doc/assets/61026903/1da7a684-b537-4deb-8902-5e00d52fe751)
