### ISSUE TITLE
Ошибка в документации - поле reserve для позиции заказа

### ISSUE THREAD

**Issue by dargoltz** [moysklad/api-remap-1.2-doc#551]
Добрый день! Поле reserve для позиции в заказа обозначено как int в документации, однако в ответах на запрос получения позиций в заказе reserve всегда double, что логично, т.к. резерв позиции описывается по его количеству, которое в свою очередь тоже не является целочисленным типом.

**Comment by dargoltz** [comment]
Вообще-то не совсем понятно - на скриншоте reserve 0, 
![изображение](https://github.com/moysklad/api-remap-1.2-doc/assets/45558945/8ef50ae7-3e5b-42f5-9f36-be5b3c6cc349),
но когда мы резолвили у себя ответ на запрос позиций в заказе ожидая reserve как int, в случае, если reserve != 0, мы получали такую ошибку 
![изображение](https://github.com/moysklad/api-remap-1.2-doc/assets/45558945/508dcadd-6295-45da-879c-0248bb18dfeb)

**Comment by Vurikus** [comment]
Добрый день. В документации опечатка. Спасибо, поправили
