### ISSUE TITLE
Проблемы при большом количестве запросов

### ISSUE THREAD

**Issue by CherrySuryp** [moysklad/api-remap-1.2-doc#568]
Здравствуйте!

Пишу интеграцию для аналитики, мне требуется делать около 3000 запросов к Вашему сервису, для полученя позиций приемок и отгрузок.

Сначала делал синхронные последовательные запросы, все было ок, но RPS был всего лишь 4

Потом решил поднять RPS - стал делать запросы асинхроннно, и начались проблемы. 2 из 5 попыток сервис падает в ошибку, при том что ограничения Ваши соблюдаются(ограничение вашего сервиса 15 RPS,  я ограничиваю до 10 RPS)
Так же ограничиваю общее количество запросов до 200 на одну асинхронную задачу

При таких ограничениях ошибки все равно вылазят рандомно и каждый раз что-то новое))

Подскажите, проблема на Вашей стороне, или Я что то не учитываю?

![Screenshot from 2023-07-26 14-46-11](https://github.com/moysklad/api-remap-1.2-doc/assets/35612551/fe338830-8daa-40f5-b5a6-430b33244988)

**Comment by CherrySuryp** [comment]
`import asyncio
import json

import aiohttp
import time

from tqdm import tqdm


async def make_request(session, ms_id):
    async with session.get(
            f"https://online.moysklad.ru/api/remap/1.2/entity/demand/"
            f"{ms_id}/positions",
            headers={
                "Authorization": f"Bearer <token>"
            },
    ) as response:
        result = await response.json()
        try:
            return result['rows']
        except KeyError:
            return result


def slice_list_to_chunks(to_slice: list, chunk_size: int):
    for piece in range(0, len(to_slice), chunk_size):
        yield to_slice[piece:piece + chunk_size]


async def send_requests():
    start_time = time.time()

    result = []
    with open('dataset.json', 'r', encoding='utf8') as f:
        ids = json.load(f)

    chunk_size = 200
    chunks = list(slice_list_to_chunks(ids, chunk_size))

    print(f'{len(ids)} requests to make')
    print(f"{chunk_size} requests per chunk")

    async with aiohttp.ClientSession() as session:
        for chunk in chunks:
            tasks = []
            request_interval = 3 / 35  # Интервал между запросами в секундах

            for ms_id in tqdm(chunk, desc='Async gather fetching data...', colour='GREEN'):
                task = asyncio.ensure_future(make_request(session, ms_id))
                tasks.append(task)
                await asyncio.sleep(request_interval)  # Ожидание перед следующим запросом

            responses = await asyncio.gather(*tasks)
            responses = responses

            result.extend(responses)

    with open('res.json', 'w', encoding='utf8') as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    elapsed_time = time.time() - start_time

    print(f"Execution time: {elapsed_time} сек.")
    print(f"Requests made {len(ids)}")
    print(f'Actual RPS {len(ids) / elapsed_time}')


loop = asyncio.get_event_loop()
loop.run_until_complete(send_requests())`

**Comment by CherrySuryp** [comment]
`import asyncio
import json

import aiohttp
import time

from tqdm import tqdm


async def make_request(session, ms_id):
    async with session.get(
            f"https://online.moysklad.ru/api/remap/1.2/entity/demand/"
            f"{ms_id}/positions",
            headers={
                "Authorization": f"Bearer <token>"
            },
    ) as response:
        result = await response.json()
        try:
            return result['rows']
        except KeyError:
            return result


def slice_list_to_chunks(to_slice: list, chunk_size: int):
    for piece in range(0, len(to_slice), chunk_size):
        yield to_slice[piece:piece + chunk_size]


async def send_requests():
    start_time = time.time()

    result = []
    with open('dataset.json', 'r', encoding='utf8') as f:
        ids = json.load(f)

    chunk_size = 200
    chunks = list(slice_list_to_chunks(ids, chunk_size))

    print(f'{len(ids)} requests to make')
    print(f"{chunk_size} requests per chunk")

    async with aiohttp.ClientSession() as session:
        for chunk in chunks:
            tasks = []
            request_interval = 3 / 35  # Интервал между запросами в секундах

            for ms_id in tqdm(chunk, desc='Async gather fetching data...', colour='GREEN'):
                task = asyncio.ensure_future(make_request(session, ms_id))
                tasks.append(task)
                await asyncio.sleep(request_interval)  # Ожидание перед следующим запросом

            responses = await asyncio.gather(*tasks)
            responses = responses

            result.extend(responses)

    with open('res.json', 'w', encoding='utf8') as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    elapsed_time = time.time() - start_time

    print(f"Execution time: {elapsed_time} сек.")
    print(f"Requests made {len(ids)}")
    print(f'Actual RPS {len(ids) / elapsed_time}')


loop = asyncio.get_event_loop()
loop.run_until_complete(send_requests())`

**Comment by CherrySuryp** [comment]
![image](https://github.com/moysklad/api-remap-1.2-doc/assets/35612551/bad0ecdf-2f57-40da-a253-12cfa2f28130)

**Comment by SergeyTru** [comment]
Добрый день.
Может ли быть такое, что кто-то ещё отправляет запросы от этого пользователя? В этом случае лимиты будут общие.
В заголовке ответа есть `x-ratelimit-remaining`, который показывает, сколько запросов можно сделать. Логирование этого поля может помочь найти причину.
Если это новый аккаунт для разработки, можно узнать список запросов у поддержки.

**Comment by CherrySuryp** [comment]
Так же, кстати, пробовал делить запросы между несколькими пользователями(500 на одного, 500 на другого итд) и ошибка все равно возникала так же рандомно))
Чудеса

**Comment by CherrySuryp** [comment]
При этом иногда все таки все проходит успешно
![image](https://github.com/moysklad/api-remap-1.2-doc/assets/35612551/9dfcdb75-0aa4-43ab-a97d-548b26abecbd)

**Comment by SergeyTru** [comment]
У поддержки можно запросить, были ли ошибки на нашей стороне на аккаунте. Возможно, проблема в реализации многопоточности.

**Comment by CherrySuryp** [comment]
Хорошо, спасибо
