### ISSUE TITLE
Ошибка метода https://online.moysklad.ru/api/remap/1.2/report/stock/all?operation.rowsPerPage=10000

### ISSUE THREAD

**Issue by GSlav080** [moysklad/api-remap-1.2-doc#580]
Возвращает себестоимость с ошибкой в знаке. Т.е себестоймость призодиться делить на 100, что бы получить верное значение

**Comment by SergeyTru** [comment]
remap 1.2 работает с целыми числами в денежных полях.
Такой подход позволяет исключить ошибки округления.
Для расчётов в рублях копейки важны, поэтому суммы выводятся в копейках.
В некоторых полях могут быть дробные копейки, но для единообразия выводится все равно в копейках.

В документации это отражается. Например, [заказ покупателя](https://dev.moysklad.ru/doc/api/remap/1.2/documents/#dokumenty-zakaz-pokupatelq-zakazy-pokupatelej). Если в каком-то разделе не написали явно, напишите, пожалуйста, в каком

**Comment by SergeyTru** [comment]
Увидел, что в отчёте остатков.
Напишем в документации, спасибо

**Comment by GSlav080** [comment]
Понял, спасибо больше.Не могли бы подсказать, как через апи можно получить вот эту информацию.Всё перепробовал, буду оочень благодарен!
![image](https://github.com/moysklad/api-remap-1.2-doc/assets/89138372/344b73fa-05d3-4e8f-877f-a137f3d13a8a)

**Comment by GSlav080** [comment]
Нужны именно остатки по этим перемещениям
