### ISSUE TITLE
Запрос на получения фильтрованного списка заказов совмещенный с экспандом по позициям не возвращщает экспанд

### ISSUE THREAD

**Issue by yevgeny-sotnikov** [moysklad/api-remap-1.2-doc#587]
При запросе

`https://online.moysklad.ru/api/remap/1.2/entity/customerorder?expand=positions&filter=state=https://online.moysklad.ru/api/remap/1.2/entity/customerorder/metadata/states/60eedd2e-963a-11e8-9ff4-34e8001a1d07`

возвращщается список заказов без развернутого списка позиций, только метадата

**Comment by agrebenshchikov** [comment]
Здравствуйте, для expand в эндпоинте списка к запросу нужно добавить параметр limit не больше 100 (&limit=100). В этом разделе есть описание https://dev.moysklad.ru/doc/api/remap/1.2/#mojsklad-json-api-obschie-swedeniq-zamena-ssylok-ob-ektami-s-pomosch-u-expand

**Comment by yevgeny-sotnikov** [comment]
> Здравствуйте, для expand в эндпоинте списка к запросу нужно добавить параметр limit не больше 100 (&limit=100). В этом разделе есть описание https://dev.moysklad.ru/doc/api/remap/1.2/#mojsklad-json-api-obschie-swedeniq-zamena-ssylok-ob-ektami-s-pomosch-u-expand

А можно-ли выбрать как-то следующщие 100 элементов? Есть ли параметр  offset или что-то в этом роде? Заранее спасибо

**Comment by agrebenshchikov** [comment]
Возможность "листания" страниц описана в этом разделе https://dev.moysklad.ru/doc/api/remap/1.2/workbook/#workbook-fil-traciq-listanie-poisk-i-sortirowka

**Comment by yevgeny-sotnikov** [comment]
Понял, спасибо!
