### ISSUE TITLE
Не получается переместить товар в архив

### ISSUE THREAD

**Issue by TywinLanni** [moysklad/api-remap-1.2-doc#629]
PUT /api/remap/1.2/entity/product/:productId отправляю сюда json
`{
    "name" : "test",
    "article" : "ARCH",
    "archived" : true
}`

По итогу изменяется только имя относительно старого значения, артикул остаётся прежним и товар не опадает в архив. Что делаю не так?

**Comment by Vurikus** [comment]
Добрый день. Действия выглядят правильными. Товар должен стать архивным. Если проблема еще актуально, то рекомендуем обратиться в техподдержку
![image](https://github.com/moysklad/api-remap-1.2-doc/assets/61026903/4281a044-142d-4197-9a0b-d1d7fd76c549)

![image](https://github.com/moysklad/api-remap-1.2-doc/assets/61026903/1d5b807d-84b1-49d4-aa42-ac452f478978)

**Comment by TywinLanni** [comment]
Спасибо!
