### ISSUE TITLE
Ошибка в документации

### ISSUE THREAD

**Issue by dektrian-git** [moysklad/api-remap-1.2-doc#652]
В блоке "Пример того, в каком виде будут передаваться данные" у Описание вебхука на изменение остатков в свойстве reportUrl у ссылки старый параметр fromDate, сейчас приходит changedSince.
![dev moysklad ru](https://github.com/moysklad/api-remap-1.2-doc/assets/65763402/effe0c5d-2234-4fa4-99b8-37f8a276ffbe)

**Comment by Vurikus** [comment]
Спасибо за комментарий. Поправим
