### ISSUE TITLE
Опечатка в url 

### ISSUE THREAD

**Issue by Sainekt** [moysklad/api-remap-1.2-doc#716]
Получение позиций заказ поставщику. 
Опечатка в url 
![Снимок экрана от 2024-07-14 13-40-22](https://github.com/user-attachments/assets/e66d7bc7-6e60-4d30-8623-166070984c0c)

**Comment by Vurikus** [comment]
Заказ поставщика (purchaseorder) в url идет в нижнем регистре. 
Спасибо, поправим
