### ISSUE TITLE
Опечатка в url

### ISSUE THREAD

**Issue by svj4** [moysklad/api-remap-1.2-doc#722]
Опечатка в примере https://dev.moysklad.ru/doc/api/remap/1.2/dictionaries/#suschnosti-nastrojki-kompanii-poluchit-metadannye-nastroek-kompanii (ссылка на старую апи)

![image](https://github.com/user-attachments/assets/cf647192-258c-4442-93f6-a6396bb839e5)

**Comment by Vurikus** [comment]
Спасибо. Поправим
