### ISSUE TITLE
Ошибка 1021 в запросе /api/remap/1.2/entity/productfolder/

### ISSUE THREAD

**Issue by Vladislav-Shi** [moysklad/api-remap-1.2-doc#726]
Ошибка 1021 в запросе /api/remap/1.2/entity/productfolder/
При указании meta у продукта его не может найти (объект существует, если перейти по href)

**Comment by SergeyTru** [comment]
Добрый день. `productfolder` - это группа товаров. Нельзя получить Группу товаров, передавая 
товар в url path. Получить Продукт с развернутыми данными по Группе товаров можно только через `/api/remap/1.2/entity/product/{UUID}?expand=productFolder` (для товаров в корне поля не будет).

Если решение не поможет, предлагаю обратится в поддержку.
