### ISSUE TITLE
Ошибка запроса /api/remap/1.2/entity/customerorder/

### ISSUE THREAD

**Issue by TeroProm** [moysklad/api-remap-1.2-doc#746]
Данный запрос:
https://api.moysklad.ru/api/remap/1.2/entity/customerorder/metadata/attributes/0cb6af65-74b6-11ed-0a80-07100083c957=%2ABcZ6%2FO1I
Возвращает ошибку:
{"errors":[{"error":"Неопознанный путь: https://api.moysklad.ru/api/remap/1.2/entity/customerorder/metadata/attributes/0cb6af65-74b6-11ed-0a80-07100083c957=%2ABcZ6%2FO1I","code":1002,"moreInfo":"https://dev.moysklad.ru/doc/api/remap/1.2/#error_1002"}]}

**Comment by krvms12** [comment]
ошибка: Неопознанный путь
корректный путь запроса:
https://api.moysklad.ru/api/remap/1.2/entity/customerorder/metadata/attributes/id
`=%2ABcZ6%2FO1I` - лишнее
