### ISSUE TITLE
Невозможно получить изображение товара нормального размера

### ISSUE THREAD

**Issue by Pr1ncee** [moysklad/api-remap-1.2-doc#769]
После запроса на этот ендпоинт (https://api.moysklad.ru/api/remap/1.2/entity/product/00a52938-5f8b-11ee-0a80-1089001b8c71/images) мы получаем такой респонс:
![image](https://github.com/user-attachments/assets/d1cc5aba-4492-4ad3-88cc-3a224d7c936a)
Изображение `miniature` и `tiny` работает корректно (открывается картинка), однако изображение нормального размера имеет тип `image`, но `mediaType` - JSON, а не `image/png`, как `miniature` и `tiny`:
```
"meta": {
  "href": "https://api.moysklad.ru/api/remap/1.2/entity/product/00a52938-5f8b-11ee-0a80-1089001b8c71/images/9cf16b79-0c33-49ea-83b0-66ed661af40f",
  "type": "image",
  "mediaType": "application/json",
  "downloadHref": "https://api.moysklad.ru/api/remap/1.2/download/9cf16b79-0c33-49ea-83b0-66ed661af40f"
}
```
Если сделать запрос по ссылке из `meta/href`, мы получаем такой респонс:
![image](https://github.com/user-attachments/assets/81527785-9e25-44de-bbc6-702b6b3ac7c4)

**Comment by krvms12** [comment]
Получить ссылку на скачивание изображения можно обратившись по адресу указанному в поле downloadHref у меты изображения.
