### ISSUE TITLE
Обновление группы (ProductFolder)

### ISSUE THREAD

**Issue by Milig01** [moysklad/api-remap-1.2-doc#783]
При обновлении группы в объекте не указываю поле ProductFolder, но в моем складе группа не становиться самой верхней группой, а остается в прежнем расположении. Не получается через api вложенную группу сделать корневой, чтобы pathName стал равен пустой строке

**Comment by krvms12** [comment]
pathName - является полем только для чтения
для указания родительской группы используется поле productFolder
для того чтобы сделать группу корневой необходимо указать в теле запроса PUT:
"productFolder": null
