### ISSUE TITLE
Редактирование цен

### ISSUE THREAD

**Issue by TeroProm** [moysklad/api-remap-1.2-doc#798]
В вашем сервисе есть возможность редактировать цены из документа приемки. Как это сделать через API?

**Comment by agrebenshchikov** [comment]
Информация по работе с api есть в нашей документации, непосредственно по изменению документа Приемки по ссылке: https://dev.moysklad.ru/doc/api/remap/1.2/documents/#dokumenty-priemka-izmenit-poziciu
По остальным вопросам можете обращаться в нашу службу техподдержки https://www.moysklad.ru/poleznoe/shkola-torgovli/tekhpodderzhka-moegosklada/?ysclid=m4vimtc8xj523869824
