### ISSUE TITLE
Неверный пример customerOrder

### ISSUE THREAD

**Issue by darkvovich** [moysklad/api-remap-1.2-doc#812]
В документации в [разделе про Фильтрацию](https://dev.moysklad.ru/doc/api/remap/1.2/index.html#mojsklad-json-api-obschie-swedeniq-fil-traciq-wyborki-s-pomosch-u-parametra-filter) указан пример

`https://api.moysklad.ru/api/remap/1.2/entity/customerOrder?filter=state.name=Новый;state.name=Принят`

который не работает, т.к. правильно писать customerorder (lowercase)

**Comment by Vurikus** [comment]
Добрый день. Спасибо, поправим
