### ISSUE TITLE
Нерабочий пример фильтрации по товарам

### ISSUE THREAD

**Issue by darkvovich** [moysklad/api-remap-1.2-doc#813]
В доке https://dev.moysklad.ru/doc/api/remap/1.2/index.html#mojsklad-json-api-obschie-swedeniq-fil-traciq-wyborki-s-pomosch-u-parametra-filter
приведен пример фильтра по товару 
`filter=productid=94975104-3cad-11e8-1e44-bd4d00000084`
но он не работает для customerorder

**Comment by Vurikus** [comment]
Добрый день. Не совсем так. В документации говорится фильтрация по полю (нужно подставить название поля как оно называется в сущности). Поля с названием productid нет в заказе покупателя (customerorder), поэтому данный фильтр не будет работать
